### PR TITLE
Updates dependencies to handle vulnerabilities in activesupport

### PR DESCRIPTION
**Pull request by csaunders**
Please review @fw42 @EiNSTeiN-

### CODE REVIEW

**Comment by fw42** [comment]
tests are failing

**Comment by fw42** [comment]
I think tests failed because circle is running Ruby 1.9 for some reason

**Comment by fw42** [comment]
Code looks good to me. Why do we even run both travis and circle here?

**Comment by csaunders** [comment]
Probably has to do with the default shipit.yml file.
I'll look at that and replace the yaml file such that it doesn't run the tests through CircleCI

**Pull request merged**
